When in offline mode app crashes when clicking on Audio
Adventech/sabbath-school-ios pull request #99
Opened 2022-03-10 20:00 UTC by EmersonCarpes

# What did you change:

- Added a safe way to access array position "avoiding index out of range error"

# Merge checklist

- [ ] Automated (unit/ui) tests
- [x] Manual tests

2022-03-11 23:55 UTC, VitalikL requested changes

2022-03-11 23:55 UTC, VitalikL commented on Sabbath School/Common/Extensions/Array.swift
> +//
Can you please update with the standard comment header, similar to what you see in other files

2022-03-12 17:32 UTC, EmersonCarpes commented on Sabbath School/Common/Extensions/Array.swift
> +//
Done!

2022-03-13 04:19 UTC, VitalikL approved these changes
We can update to 2022 as well 👍

2022-03-16 11:10 UTC, merged